### ISSUE TITLE
unable to install dependencies 

### ISSUE THREAD

**Issue by pociej** [0xProject/0x-nextjs-demo-app#3]
When try to npm install : 
dzik@dziks-iMac 0x-nextjs-demo-app % npm install connectkit wagmi viem

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: 0x-nextjs-swap-pages@0.1.0
npm ERR! Found: viem@0.3.50
npm ERR! node_modules/viem
npm ERR!   viem@"^0.3.50" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer viem@"^1.0.0" from connectkit@1.5.2
npm ERR! node_modules/connectkit
npm ERR!   connectkit@"^1.4.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/dzik/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dzik/.npm/_logs/2023-08-28T11_25_43_919Z-debug-0.log

**Comment by pociej** [comment]
After I updated package.json to use newest versions of `wagmi` and `viem` it started to throw 

```
- error ./node_modules/@walletconnect/legacy-client/dist/esm/socket.js:3:0
Module not found: Can't resolve 'ws'
```

I didnt check yet why @walletconnect is in the project but seems it is missing peerDependency on 'ws' so i temporary added it to package.json which make project finally working without using both npm and yarn. Interesting that pnpm with `node-linker=hoisted` just worked. Defienitly some deeper investigation is need in dependency tree, however with what i have now it is at least running. Im open to make PR if you want.

**Comment by jlin27** [comment]
Thanks for reporting this @pociej. To answer your first question, ConnectKit uses WalletConnect's SDK to help connect wallets ([docs](https://docs.family.co/connectkit/getting-started#getting-started)). 
If you get a chance to make a PR, we'd be happy to review. Much appreciated!

**Comment by hzhu** [comment]
Thanks @jlin27! Fixed in https://github.com/0xProject/0x-nextjs-demo-app/pull/5.
