### ISSUE TITLE
npm and yarn used in same project. 

### ISSUE THREAD

**Issue by pociej** [0xProject/0x-nextjs-demo-app#4]
What is a reason for having both package-lock and yarn.lock in same project? And why running instructions are usign two mentioned package managers? This seems to be unusual and not recommended way.

**Comment by hzhu** [comment]
Thank you for opening this issue, @pociej. We intend to exclusively use npm and will address this issue shortly.

**Comment by hzhu** [comment]
Fixed in https://github.com/0xProject/0x-nextjs-demo-app/pull/5.
