### ISSUE TITLE
Outdated README

### ISSUE THREAD

**Issue by hzhu** [0xProject/0x-nextjs-demo-app#6]
It appears that the README has instructions that include both npm and yarn 👀 .

**Comment by jlin27** [comment]
Thank you ser. Updated! Commit: https://github.com/0xProject/0x-nextjs-demo-app/commit/5284cb7d52372f096a4136782d50a5658e47aabd

**Comment by IsoBitzzz** [comment]
[Gasless API Demo App (Next.js App Router)](https://github.com/0xProject/0x-examples/tree/main/tx-relay-next-app)

This is broken in the readme also now.
